### ISSUE TITLE
Window frame should support bounded preceding

### ISSUE THREAD

**Issue by nimish** [facebook/presto#3301] opened 2015-07-17 21:09 UTC
Hi,

PrestoQueryFailedException: Window frame RANGE {PRECEDING, FOLLOWING} is only supported with UNBOUNDED

Is coming up pretty often for me in queries that ought to be done in window functions but end up having to be done via joins.

Is this something easily added?

**Comment by electrum** [comment] 2015-07-18 00:22
Can you use ROWS instead of RANGE? It is supported for that.

**Comment by ntelang** [comment] 2015-07-18 13:43
Possibly--I will check whether duplication is an issue

**Comment by cberner** [comment] 2015-07-20 19:38
Duplicate of #2433

**Closed by cberner** 2015-07-20 19:38 UTC
