### ISSUE TITLE
NullPointerException when trying to EXPLAIN RENAME

### ISSUE THREAD

**Issue by cberner** [facebook/presto#1812] opened 2014-10-14 20:37 UTC
This results in an exception: "EXPLAIN ALTER TABLE orders RENAME TO renamed_orders"

java.lang.NullPointerException
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
com.facebook.presto.sql.planner.LogicalPlanner.createRelationPlan(LogicalPlanner.java:173)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:79)
com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:104)
com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:66)
com.facebook.presto.sql.analyzer.StatementAnalyzer.getQueryPlan(StatementAnalyzer.java:510)
com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:479)
com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:106)
com.facebook.presto.sql.tree.Explain.accept(Explain.java:53)
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:24)
com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:204)
com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:189)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:150)
com.facebook.presto.execution.SqlQueryManager$QueryStarter$QuerySubmitter$2.run(SqlQueryManager.java:465)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
java.lang.Thread.run(Thread.java:745)

**Comment by cawallin** [comment] 2015-07-29 02:50
duplicate of #1589

**Comment by cawallin** [comment] 2015-08-03 16:57
@cberner can you close this one please?

**Closed** 2015-08-03 17:32 UTC
Labels: bug
