### ISSUE TITLE
Expected LIST column ... entry field 0 to be named 'array_element', but is named array

### ISSUE THREAD

**Issue by danoyoung** [facebook/presto#3227] opened 2015-07-07 00:05 UTC
Hello,

I have Hive 0.13 (EMR) with Presto 0.109 running where I'm trying to query some Parquet files in HDFS.   The Hive query seems to work, but when I try to query the same data via Presto, I get an error.  It seems to have something to do with NULL Array elements in one of the Parquet columns.  If I run non "select *" type queries that do not include the ARRAY column, the queries work.  If I try select * I get the following error:

Expected LIST column 'actionables' entry field 0 to be named 'array_element', but is named array

Using EMR w/ Hive 0.13, Presto .109 

See:

https://www.refheap.com/2074a5a8b583e10aa0dafb10c

**Comment by nezihyigitbasi** [comment] 2015-07-07 00:27
@danoyoung I guess the problem is Presto uses the convention Parquet uses to name array elements [here](https://github.com/apache/parquet-mr/blob/parquet-1.6.0rc3/parquet-hive/parquet-hive-storage-handler/src/main/java/org/apache/hadoop/hive/ql/io/parquet/convert/HiveSchemaConverter.java#L104) while the data you are querying is probably written by Spark which uses a different convention, see [this](https://github.com/apache/spark/blob/v1.3.0/sql/core/src/main/scala/org/apache/spark/sql/parquet/ParquetConverter.scala#L68) and this [jira ticket](https://issues.apache.org/jira/browse/SPARK-5508).

**Comment by danoyoung** [comment] 2015-07-07 02:10
@nezihyigitbasi that seems to be the case, using spark 1.4 and the HiveContext to convert a JsonRDD to a Parquet file (via SparkSQL).  Is there a workaround on the Presto side? 

MBP-200729:parquet-tools dan.young$ ~/local/bin/parquet-tools schema -d ~/temp/part-r-00001.gz.parquet 
message root {
  optional group actionables (LIST) {
    repeated group bag {
      optional binary array (UTF8);
    }
  }
  optional int64 created;
  optional binary currencycode (UTF8);
  optional int64 displayorder;
  optional binary eventid (UTF8);
  optional binary eventtype (UTF8);
  optional int64 externallinkid;
  optional binary location (UTF8);
  optional double maxactualpriceconv;
  optional double maxactualpriceusd;
  optional double maxstrikeoutpriceconv;
  optional double maxstrikeoutpriceusd;
  optional int64 messagedate;
  optional double minactualpriceconv;
  optional double minactualpriceusd;
  optional double minstrikeoutpriceconv;
  optional double minstrikeoutpriceusd;
  optional int64 preuserid;
  optional binary pricingorigination (UTF8);
  optional int64 productfulfillmentid;
  optional int64 quantity;
  optional binary recommendationsource (UTF8);
  optional double recoscore;
  optional binary referringeventid (UTF8);
  optional int64 sessionordinal;
  optional binary sympozsessionid (UTF8);
  optional int64 thingid;
  optional binary thingtype (UTF8);
  optional int64 userid;
}

creator: parquet-mr version 1.6.0rc3
extra: org.apache.spark.sql.parquet.row.metadata = {"type":"struct","fields":[{"name":"actionables","type":{"type":"array","elementType":"string","containsNull":true},"nullable":true,"metadata":{}},{"name":"created","type":"long","nullable":true,"metadata":{}},{"name":"currencycode","type":"string","nullable":true,"metadata":{}},{"name":"displayorder","type":"long","nullable":true,"metadata":{}},{"name":"eventid","type":"string","nullable":true,"metadata":{}},{"name":"eventtype","type":"string","nullable":true,"metadata":{}},{"name":"externallinkid","type":"long","nullable":true,"metadata":{}},{"name":"location","type":"string","nullable":true,"metadata":{}},{"name":"maxactualpriceconv","type":"double","nullable":true,"metadata":{}},{"name":"maxactualpriceusd","type":"double","nullable":true,"metadata":{}},{"name":"maxstrikeoutpriceconv","type":"double","nullable":true,"metadata":{}},{"name":"maxstrikeoutpriceusd","type":"double","nullable":true,"metadata":{}},{"name":"messagedate","type":"long","nullable":true,"metadata":{}},{"name":"minactualpriceconv","type":"double","nullable":true,"metadata":{}},{"name":"minactualpriceusd","type":"double","nullable":true,"metadata":{}},{"name":"minstrikeoutpriceconv","type":"double","nullable":true,"metadata":{}},{"name":"minstrikeoutpriceusd","type":"double","nullable":true,"metadata":{}},{"name":"preuserid","type":"long","nullable":true,"metadata":{}},{"name":"pricingorigination","type":"string","nullable":true,"metadata":{}},{"name":"productfulfillmentid","type":"long","nullable":true,"metadata":{}},{"name":"quantity","type":"long","nullable":true,"metadata":{}},{"name":"recommendationsource","type":"string","nullable":true,"metadata":{}},{"name":"recoscore","type":"double","nullable":true,"metadata":{}},{"name":"referringeventid","type":"string","nullable":true,"metadata":{}},{"name":"sessionordinal","type":"long","nullable":true,"metadata":{}},{"name":"sympozsessionid","type":"string","nullable":true,"metadata":{}},{"name":"thingid","type":"long","nullable":true,"metadata":{}},{"name":"thingtype","type":"string","nullable":true,"metadata":{}},{"name":"userid","type":"long","nullable":true,"metadata":{}}]}

file schema: root
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
actionables: OPTIONAL F:1
.bag: REPEATED F:1
..array: OPTIONAL BINARY O:UTF8 R:1 D:3
created: OPTIONAL INT64 R:0 D:1
currencycode: OPTIONAL BINARY O:UTF8 R:0 D:1
displayorder: OPTIONAL INT64 R:0 D:1
eventid: OPTIONAL BINARY O:UTF8 R:0 D:1
eventtype: OPTIONAL BINARY O:UTF8 R:0 D:1
externallinkid: OPTIONAL INT64 R:0 D:1
location: OPTIONAL BINARY O:UTF8 R:0 D:1
maxactualpriceconv: OPTIONAL DOUBLE R:0 D:1
maxactualpriceusd: OPTIONAL DOUBLE R:0 D:1
maxstrikeoutpriceconv: OPTIONAL DOUBLE R:0 D:1
maxstrikeoutpriceusd: OPTIONAL DOUBLE R:0 D:1
messagedate: OPTIONAL INT64 R:0 D:1
minactualpriceconv: OPTIONAL DOUBLE R:0 D:1
minactualpriceusd: OPTIONAL DOUBLE R:0 D:1
minstrikeoutpriceconv: OPTIONAL DOUBLE R:0 D:1
minstrikeoutpriceusd: OPTIONAL DOUBLE R:0 D:1
preuserid: OPTIONAL INT64 R:0 D:1
pricingorigination: OPTIONAL BINARY O:UTF8 R:0 D:1
productfulfillmentid: OPTIONAL INT64 R:0 D:1
quantity: OPTIONAL INT64 R:0 D:1
recommendationsource: OPTIONAL BINARY O:UTF8 R:0 D:1
recoscore: OPTIONAL DOUBLE R:0 D:1
referringeventid: OPTIONAL BINARY O:UTF8 R:0 D:1
sessionordinal: OPTIONAL INT64 R:0 D:1
sympozsessionid: OPTIONAL BINARY O:UTF8 R:0 D:1
thingid: OPTIONAL INT64 R:0 D:1
thingtype: OPTIONAL BINARY O:UTF8 R:0 D:1
userid: OPTIONAL INT64 R:0 D:1

row group 1: RC:50002 TS:2752399 OFFSET:4
--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
actionables: 
.bag: 
..array:  BINARY GZIP DO:0 FPO:4 SZ:11352/19701/1.74 VC:54369 ENC:PLAIN_DICTIONARY,RLE
created:  INT64 GZIP DO:0 FPO:11356 SZ:68444/148156/2.16 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
currencycode:  BINARY GZIP DO:0 FPO:79800 SZ:5598/9731/1.74 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
displayorder:  INT64 GZIP DO:0 FPO:85398 SZ:9272/52564/5.67 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
eventid:  BINARY GZIP DO:0 FPO:94670 SZ:403972/1300219/3.22 VC:50002 ENC:BIT_PACKED,PLAIN,RLE
eventtype:  BINARY GZIP DO:0 FPO:498642 SZ:5574/12621/2.26 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
externallinkid:  INT64 GZIP DO:0 FPO:504216 SZ:26284/46941/1.79 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
location:  BINARY GZIP DO:0 FPO:530500 SZ:11544/25318/2.19 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
maxactualpriceconv:  DOUBLE GZIP DO:0 FPO:542044 SZ:33136/62316/1.88 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
maxactualpriceusd:  DOUBLE GZIP DO:0 FPO:575180 SZ:27889/54369/1.95 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
maxstrikeoutpriceconv:  DOUBLE GZIP DO:0 FPO:603069 SZ:23375/44353/1.90 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
maxstrikeoutpriceusd:  DOUBLE GZIP DO:0 FPO:626444 SZ:21458/38371/1.79 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
messagedate:  INT64 GZIP DO:0 FPO:647902 SZ:68444/148156/2.16 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
minactualpriceconv:  DOUBLE GZIP DO:0 FPO:716346 SZ:33013/62068/1.88 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
minactualpriceusd:  DOUBLE GZIP DO:0 FPO:749359 SZ:27657/54209/1.96 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
minstrikeoutpriceconv:  DOUBLE GZIP DO:0 FPO:777016 SZ:23292/44329/1.90 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
minstrikeoutpriceusd:  DOUBLE GZIP DO:0 FPO:800308 SZ:21335/38395/1.80 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
preuserid:  INT64 GZIP DO:0 FPO:821643 SZ:26914/46581/1.73 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
pricingorigination:  BINARY GZIP DO:0 FPO:848557 SZ:9871/16827/1.70 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
productfulfillmentid:  INT64 GZIP DO:0 FPO:858428 SZ:976/1795/1.84 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
quantity:  INT64 GZIP DO:0 FPO:859404 SZ:174/169/0.97 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
recommendationsource:  BINARY GZIP DO:0 FPO:859578 SZ:7941/16265/2.05 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
recoscore:  DOUBLE GZIP DO:0 FPO:867519 SZ:27920/39199/1.40 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
referringeventid:  BINARY GZIP DO:0 FPO:895439 SZ:61311/135239/2.21 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
sessionordinal:  INT64 GZIP DO:0 FPO:956750 SZ:16185/33752/2.09 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
sympozsessionid:  BINARY GZIP DO:0 FPO:972935 SZ:55513/114760/2.07 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
thingid:  INT64 GZIP DO:0 FPO:1028448 SZ:88630/136165/1.54 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
thingtype:  BINARY GZIP DO:0 FPO:1117078 SZ:6023/10684/1.77 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
userid:  INT64 GZIP DO:0 FPO:1123101 SZ:23902/39146/1.64 VC:50002 ENC:PLAIN_DICTIONARY,BIT_PACKED,RLE
MBP-200729:parquet-tools dan.young$

**Comment by danoyoung** [comment] 2015-07-07 02:13
or a work around on the spark side....

**Comment by nezihyigitbasi** [comment] 2015-07-07 17:25
@danoyoung AFAIK there is currently no workaround for this at Presto side (and same for Spark as far as I can see from the related jira tickets which are still open). Looking at the [Parquet compatibility rules](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#backward-compatibility-rules) Presto should be able to read your files according to rule 4. 

@dain What do you think?

**Comment by danoyoung** [comment] 2015-08-07 15:12
@dain can you provide any insight on how to resolve this?

**Comment by danoyoung** [comment] 2015-08-07 15:53
I can run queries against the Parquet data in Hive:

hive> select thing_id,thing_type,min_strikeout_price_usd from conversion_event_2 where dt='2015-08-02' limit 5;
Total jobs = 1
Launching Job 1 out of 1
Number of reduce tasks is set to 0 since there's no reduce operator
Starting Job = job_1438957985586_0007, Tracking URL = http://foo:9046/proxy/application_1438957985586_0007/
Kill Command = /home/hadoop/bin/hadoop job  -kill job_1438957985586_0007
Hadoop job information for Stage-1: number of mappers: 2; number of reducers: 0
2015-08-07 15:46:33,659 Stage-1 map = 0%,  reduce = 0%
2015-08-07 15:46:39,969 Stage-1 map = 50%,  reduce = 0%, Cumulative CPU 2.54 sec
2015-08-07 15:46:41,015 Stage-1 map = 100%,  reduce = 0%, Cumulative CPU 5.13 sec
MapReduce Total cumulative CPU time: 5 seconds 130 msec
Ended Job = job_1438957985586_0007
MapReduce Jobs Launched: 
Job 0: Map: 2   Cumulative CPU: 5.13 sec   HDFS Read: 30255012 HDFS Write: 147 SUCCESS
Total MapReduce CPU Time Spent: 5 seconds 130 msec
OK
62960	PATTERN	NULL
140823	PATTERN	NULL
795	PFSG	21.1
891	PFSG	22.0
3785	PFS	52.0
Time taken: 19.332 seconds, Fetched: 5 row(s)
hive> 


Try the same query in Presto:

~hadoop/presto-cli --catalog hive --schema default
presto:default> select thing_id,thing_type,min_strikeout_price_usd from conversion_event_2 where dt='2015-08-02' limit 5;

Query 20150807_154831_00018_h6ymf, FAILED, 2 nodes
Splits: 21 total, 0 done (0.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20150807_154831_00018_h6ymf failed: null

presto:default> 


java.lang.NullPointerException
	at com.facebook.presto.spi.RecordPageSource.getNextPage(RecordPageSource.java:118)
	at com.facebook.presto.operator.TableScanOperator.getOutput(TableScanOperator.java:239)
	at com.facebook.presto.operator.Driver.processInternal(Driver.java:380)
	at com.facebook.presto.operator.Driver.processFor(Driver.java:303)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:587)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)



This is the table where we have a column defined as an ARRAY<String>, it looks like the actionables column is causing the problem.....

presto:default> describe conversion_event_2
             -> ;
          Column          |      Type      | Null | Partition Key | Comment 
--------------------------+----------------+------+---------------+---------
 actionables              | array<varchar> | true | false         |         
 element                  | varchar        | true | false         |         
 created                  | bigint         | true | false         |         
.....
.....      
(31 rows)

Query 20150807_155155_00019_h6ymf, FINISHED, 2 nodes
Splits: 2 total, 2 done (100.00%)
0:00 [31 rows, 2.91KB] [281 rows/s, 26.4KB/s]

presto:default>

**Comment by electrum** [comment] 2015-08-07 18:13
Is there some way to tell by looking at the file metadata or Hive metastore metadata to know which is the correct way to read the table? If not, maybe we could add a Hive table property?

**Comment by electrum** [comment] 2015-08-07 18:13
Oh, if this is queryable in Hive, then we need to figure out what rules Hive is using and follow them.

**Comment by dain** [comment] 2015-08-07 18:14
@nezihyigitbasi I don't really know enough about Parquet to make a call.  If you think we should make a change, send a PR and @cberner or I will merge it.

**Comment by dain** [comment] 2015-08-07 18:16
@nezihyigitbasi to further clarify, I think we should have same defaults as Hive, so users aren't surprised/confused when switching Presto.  Also, we should support any behavioral Parquet flags Hive has so users can read and write data that is compatible with Hive.

**Comment by nezihyigitbasi** [comment] 2015-08-07 19:47
@dain Alright I can reproduce it and working on a fix now.

**Comment by danoyoung** [comment] 2015-08-07 21:27
@nezihyigitbasi awesome!  thank you!!!!

**Comment by nezihyigitbasi** [comment] 2015-08-17 03:04
@danoyoung #3426 is merged, can you please give it a try?

**Comment by danoyoung** [comment] 2015-08-18 14:36
@nezihyigitbasi yes, I've been out of town.  Will try today.

**Comment by danoyoung** [comment] 2015-08-18 19:06
@nezihyigitbasi I cloned master this morning and build with: mvn clean install -DskipTests 

Then I fired up an EMR cluster using the 3.8 AMI to install and configure using my custom Presto version.  I tried to run the queries against the Parquet data stored in HDFS and it still is failing.  I've pasted the output....


https://www.refheap.com/0f4aa60367e5945d1eb62ede2


I can query the data with Hive 0.13.  LMK what other debug/diagnostic information you might need.

**Comment by danoyoung** [comment] 2015-08-18 19:39
Nevermind.....my bad.  Forgot to set the hive.parquet.use-column-names=true

presto:default> select thing_id,thing_type,event_type,location from conversion_event2 where dt='2015-08-13' limit 10;
 thing_id | thing_type | event_type |               location               
----------+------------+------------+--------------------------------------
    15951 | PFS        | RENDER     | ECOMM_GALLERY                        
    10552 | PFS        | RENDER     | ECOMM_GALLERY                        
    14339 | PFS        | RENDER     | ECOMM_GALLERY                        
      275 | PFSG       | DISPLAY    | SAD_PFS_SELL_PAGE_KITS               
     5006 | PFS        | RENDER     | ECOMM_GALLERY                        
    67873 | PATTERN    | DISPLAY    | SAD_PATTERN_DETAIL_PAGE              
   104289 | PATTERN    | RENDER     | MEMBER_HOME_PATTERN_DESIGNER_SECTION 
    16346 | PFS        | RENDER     | ECOMM_GALLERY                        
    14041 | PFS        | RENDER     | ECOMM_GALLERY                        
     5622 | PFS        | RENDER     | MEMBER_HOME_PROJECTS_SECTION         
(10 rows)

**Closed** 2015-08-18 20:20 UTC
