### ISSUE TITLE
Error message for functions that don't resolve due to argument not being comparable is confusing

### ISSUE THREAD

**Issue by martint** [facebook/presto#2453] opened 2015-03-02 20:50 UTC
```select map(array[map(array[1], array[1])], array[map(array[1], array[1])])```

Fails with:

```
com.facebook.presto.spi.PrestoException: Unexpected parameters (array<map<bigint,bigint>>, array<map<bigint,bigint>>) for function map. Expected: map(array<K>, array<V>)
	at com.facebook.presto.metadata.FunctionRegistry.resolveFunction(FunctionRegistry.java:467)
	at com.facebook.presto.metadata.MetadataManager.resolveFunction(MetadataManager.java:147)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:673)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer$Visitor.visitFunctionCall(ExpressionAnalyzer.java:208)
	at com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:70)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyze(ExpressionAnalyzer.java:181)
	at com.facebook.presto.sql.analyzer.ExpressionAnalyzer.analyzeExpression(ExpressionAnalyzer.java:1019)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeExpression(TupleAnalyzer.java:1064)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.analyzeSelect(TupleAnalyzer.java:867)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:347)
	at com.facebook.presto.sql.analyzer.TupleAnalyzer.visitQuerySpecification(TupleAnalyzer.java:132)
	at com.facebook.presto.sql.tree.QuerySpecification.accept(QuerySpecification.java:98)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:502)
	at com.facebook.presto.sql.analyzer.StatementAnalyzer.visitQuery(StatementAnalyzer.java:114)
	at com.facebook.presto.sql.tree.Query.accept(Query.java:80)
	at com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
	at com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:52)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:198)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:184)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:145)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QueryQueue.lambda$null$76(SqlQueryManager.java:465)
	at com.facebook.presto.execution.SqlQueryManager$QueryStarter$QueryQueue$$Lambda$172/1007407346.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by cberner** [comment] 2015-03-02 21:02
That's not a bug, that's working as intended. The MAP type is not comparable, and the signature of map(K, V) requires that K be comparable. Therefore you can't construct a MAP from an `array<map<bigint, bigint>>`

**Comment by cberner** [comment] 2015-03-03 02:20
This is a duplicate of #2181

**Closed by cberner** 2015-03-03 02:20 UTC
