### ISSUE TITLE
Mixed case Avro/Parquet field names unqueryable, "not found in message"

### ISSUE THREAD

**Issue by Xorlev** [facebook/presto#1802] opened 2014-10-11 09:40 UTC
Hey guys,

Presto 0.79, Hive 0.13.1, hive-hadoop2 connector. Attempting to query an external hive table

```
CREATE EXTERNAL TABLE edge_logs (remoteAddr STRING, timestamp bigint, request STRING, apiKey STRING, status int, referer STRING, userAgent STRING)
PARTITIONED BY (dt string)
ROW FORMAT SERDE 'org.apache.hadoop.hive.serde2.avro.AvroSerDe'
STORED AS PARQUET
LOCATION 's3://xxxxx
```

Unfortunately, even using quoted identifiers doesn't seem to do the trick:

```
presto:default> use catalog hive;
presto:default> select count(*),"apiKey" FROM edge_logs GROUP BY "apiKey";

Query 20141011_093521_00016_kizzm, FAILED, 2 nodes
Splits: 139 total, 0 done (0.00%)
0:01 [0 rows, 0B] [0 rows/s, 0B/s]

Query 20141011_093521_00016_kizzm failed: apikey not found in message com.fullcontact.data.EdgeAccessLog {
  required binary remoteAddr (UTF8);
  required binary remoteUser (UTF8);
  required int64 timestamp;
  required binary method (ENUM);
  required binary request (UTF8);
  required binary apiKey (UTF8);
  required binary accessToken (UTF8);
  required int32 status;
  required int64 bytesSent;
  required binary referer (UTF8);
  required binary userAgent (UTF8);
  required binary forwardedFor (UTF8);
  required int64 requestTimeMs;
  required binary requestId (UTF8);
  required int64 offset;
}
```

However I have no problems with lowercase fields. If I limit a SELECT to just lowercase fields (of which there are few...) it works without issues. A `SELECT *` will return the same message.

Any easy fixes here (other than forcing all of my identifiers to be lowercase)?

**Comment by cberner** [comment] 2015-04-27 19:44
@nezihyigitbasi do you know if this is still an issue, and do you know how to fix it?

**Comment by eztzachi** [comment] 2015-04-29 00:58
Hey!
This is still an issue with Presto 0.100. and Hive 0.13.1.

I have the same issue here where one of the field names has a capital letter in the Avro schema. In Hive, the field is automatically lowercased (in terms of coulmn name), and there is no problem to run queries on this table, but It looks like Presto tries to verify the column name it gets from Hive using the Avro schema, and it fails due to case sensitivity.

**Comment by nezihyigitbasi** [comment] 2015-04-29 02:15
@cberner  I haven't seen this one before but if you check the "Limitations" section of this [page](https://cwiki.apache.org/confluence/display/Hive/Parquet), it mentions a very similar issue that has been fixed with Hive 0.14 (see HIVE-7554). 
@eztzachi Can you please provide the full stack trace that you get, and even better steps to reproduce this problem so that we can take a look?

**Comment by eztzachi** [comment] 2015-04-29 03:15
@nezihyigitbasi, since I also use Parquet HIVE-7554 might be relevant in my case as well, but the only thing I don't understand is how it is a non issue in Hive, while in Presto fails on query such a table.

The error message is exactly similar to the one mentioned above (with different field names). 
This is the server logs for the command: 
2015-04-28T16:33:15.657-0700     INFO   query-execution-199     com.facebook.presto.event.query.QueryMonitor    TIMELINE: Query 20150428_233315_00017_pnfam :: elapsed 190.00ms :: planning 9.35ms :: scheduling 181.00ms :: running 15631.00ms :: finishing 0.00ms :: begin 2015-04-28T16:33:15.465-07:00 :: end 2015-04-28T16:33:15.655-07:00

In order to reproduce it:
1. Create an avro schema with a field name that includes a capital letter.
2. Generate some data based on this schema and use Apache Parquet to serialize it.
3. Create an external table in hive that fits this schema (when I created the table I used the same key like avro - with a capital letter - Hive of course created a lowercase version for the column name), with ParquetHiveSerDe, and point it to a location that contains parquet info files:
ROW FORMAT SERDE 'parquet.hive.serde.ParquetHiveSerDe'
STORED AS
INPUTFORMAT 'parquet.hive.DeprecatedParquetInputFormat'
OUTPUTFORMAT 'parquet.hive.DeprecatedParquetOutputFormat'
INPUT <parquet-serialized-data-location>

That's it. Now try to select on the table in Hive and in Presto.

One last thought, I didn't try to reproduce it without the Parquet serialization but it is worth trying in order to isolate the issue.

**Comment by nezihyigitbasi** [comment] 2015-04-29 06:42
@eztzachi I couldn't reproduce this problem with the latest Presto. I followed your steps to create a parquet file with a single field that has an uppercase letter and I have written the data in Parquet format using the kite sdk. When I query the table I get zero rows instead of getting an exception. 

Since I couldn't reproduce it can you please start presto cli with --debug and paste here the complete stack trace that you get? It will also be nice if you can provide us a sample test dataset that I can reproduce this.

Here is the schema:
```
parquet-meta file:///users/nyigitbasi/mixed_case_avro.parquet
Picked up _JAVA_OPTIONS: -XX:MaxRAM=32g -XX:MaxRAMFraction=16 -XX:InitialRAMFraction=128
creator:     parquet-mr (build 27f71a18579ebac6db2b0e9ac758d64288b6dbff)
extra:       avro.schema = {"type":"record","name":"apiKey","namespace":"org.kitesdk.examples.data","fields":[{"name":"apiKey","type":"string"}]}

file schema: org.kitesdk.examples.data.apiKey
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
apiKey:      REQUIRED BINARY O:UTF8 R:0 D:0

row group 1: RC:100 TS:42
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
apiKey:       BINARY SNAPPY DO:0 FPO:4 SZ:46/42/0.91 VC:100 ENC:BIT_PACKED,PLAIN_DICTIONARY
```

Here is the data:
```
parquet-head  file:///users/nyigitbasi/mixed_case_avro.parquet
Picked up _JAVA_OPTIONS: -XX:MaxRAM=32g -XX:MaxRAMFraction=16 -XX:InitialRAMFraction=128
apiKey = test

apiKey = test

apiKey = test

apiKey = test

apiKey = test
```

**Comment by eztzachi** [comment] 2015-05-06 00:21
This is the complete stack trace:

    presto:default> select * from presto_debug_mixed;
    
    Query 20150506_001148_00009_9gi4y, FAILED, 2 nodes
    http://localhost:8080/v1/query/20150506_001148_00009_9gi4y?pretty
    Splits: 21 total, 0 done (0.00%)
    CPU Time: 0.0s total,     0 rows/s,     0B/s, 0% active
    Per Node: 0.0 parallelism,     0 rows/s,     0B/s
    Parallelism: 0.0
    0:01 [0 rows, 0B] [0 rows/s, 0B/s]
    
    Query 20150506_001148_00009_9gi4y failed: apikey not found in message presto.debug.avro.PrestoDebugLog {
      required binary id (UTF8);
      required binary apiKey (UTF8);
    }
    
    parquet.io.InvalidRecordException: apikey not found in message presto.debug.avro.PrestoDebugLog {
      required binary id (UTF8);
      required binary apiKey (UTF8);
    }
	at parquet.schema.GroupType.getFieldIndex(GroupType.java:104)
	at parquet.schema.GroupType.getType(GroupType.java:136)
	at com.facebook.presto.hive.ParquetHiveRecordCursor$PrestoReadSupport.init(ParquetHiveRecordCursor.java:412)
	at com.facebook.presto.hive.ParquetHiveRecordCursor.createParquetRecordReader(ParquetHiveRecordCursor.java:313)
	at com.facebook.presto.hive.ParquetHiveRecordCursor.<init>(ParquetHiveRecordCursor.java:116)
	at com.facebook.presto.hive.ParquetRecordCursorProvider.createHiveRecordCursor(ParquetRecordCursorProvider.java:68)
	at com.facebook.presto.hive.HivePageSourceProvider.getHiveRecordCursor(HivePageSourceProvider.java:129)
	at com.facebook.presto.hive.HivePageSourceProvider.createPageSource(HivePageSourceProvider.java:107)
	at com.facebook.presto.spi.classloader.ClassLoaderSafeConnectorPageSourceProvider.createPageSource(ClassLoaderSafeConnectorPageSourceProvider.java:42)
	at com.facebook.presto.split.PageSourceManager.createPageSource(PageSourceManager.java:48)
	at com.facebook.presto.operator.TableScanOperator.addSplit(TableScanOperator.java:144)
	at com.facebook.presto.operator.Driver.processNewSource(Driver.java:259)
	at com.facebook.presto.operator.Driver.processNewSources(Driver.java:224)
	at com.facebook.presto.operator.Driver.access$300(Driver.java:53)
	at com.facebook.presto.operator.Driver$DriverLockResult.close(Driver.java:508)
	at com.facebook.presto.operator.Driver.updateSource(Driver.java:202)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.createDriver(SqlTaskExecution.java:464)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunnerFactory.access$1500(SqlTaskExecution.java:431)
	at com.facebook.presto.execution.SqlTaskExecution$DriverSplitRunner.processFor(SqlTaskExecution.java:557)
	at com.facebook.presto.execution.TaskExecutor$PrioritizedSplitRunner.process(TaskExecutor.java:505)
	at com.facebook.presto.execution.TaskExecutor$Runner.run(TaskExecutor.java:639)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	
    presto:default> 


And this is the schema I am using:

    {"namespace": "presto.debug.avro",
     "type": "record",
     "name": "PrestoDebugLog",
     "fields": [
    {"name": "id", "type": "string", "default": ""},
    {"name": "apiKey", "type": "string", "default": ""}
     ]

Also, If I run the query only on the id field the query return with results:

    presto:default> select id  from presto_debug_mixed limit 10;
     id 
    ----
     29 
     42 
     22 
     1  
     14 
     14 
     48 
     32 
     26 
     20 
    (10 rows)

**Comment by nezihyigitbasi** [comment] 2015-05-06 21:00
@eztzachi I was able to reproduce your problem and the problem is fixed with master only if you set ``hive.parquet.use-column-names=false``, which will make Presto access columns by index instead of name. Can you please try and let me know? The relevant commit that fixes this issue is 0457f03bd703258e28f479d4d82cf72e97210d1b

**Comment by eztzachi** [comment] 2015-05-07 00:09
@nezihyigitbasi Thank you! It solved the issue.

**Comment by cberner** [comment] 2015-05-07 00:24
Great! Going to close this then :)

**Closed by cberner** 2015-05-07 00:24 UTC
