### ISSUE TITLE
Error: row_number():bigint is not a scalar function

### ISSUE THREAD

**Issue by electrum** [facebook/presto#4498] opened 2016-02-08 18:56 UTC
```
row_number():bigint is not a scalar function
java.lang.IllegalArgumentException
com.google.common.base.Preconditions.checkArgument(Preconditions.java:145)
com.facebook.presto.metadata.FunctionRegistry.getScalarFunctionImplementation(FunctionRegistry.java:555)
com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitFunctionCall(ExpressionInterpreter.java:812)
com.facebook.presto.sql.tree.FunctionCall.accept(FunctionCall.java:96)
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
com.facebook.presto.sql.planner.ExpressionInterpreter$Visitor.visitComparisonExpression(ExpressionInterpreter.java:642)
com.facebook.presto.sql.tree.ComparisonExpression.accept(ComparisonExpression.java:91)
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
com.facebook.presto.sql.planner.ExpressionInterpreter.optimize(ExpressionInterpreter.java:229)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.simplifyExpression(SimplifyExpressions.java:133)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:100)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitFilter(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$136(SimplePlanRewriter.java:75)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitWindow(PlanVisitor.java:105)
com.facebook.presto.sql.planner.plan.WindowNode.accept(WindowNode.java:171)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:97)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:91)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions$Rewriter.visitProject(SimplifyExpressions.java:70)
com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.rewrite(SimplePlanRewriter.java:86)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.lambda$defaultRewrite$136(SimplePlanRewriter.java:75)
java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
java.util.Iterator.forEachRemaining(Iterator.java:116)
java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter$RewriteContext.defaultRewrite(SimplePlanRewriter.java:76)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:40)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.visitPlan(SimplePlanRewriter.java:24)
com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
com.facebook.presto.sql.planner.plan.SimplePlanRewriter.rewriteWith(SimplePlanRewriter.java:29)
com.facebook.presto.sql.planner.optimizations.SimplifyExpressions.optimize(SimplifyExpressions.java:67)
com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:101)
com.facebook.presto.sql.analyzer.QueryExplainer.getLogicalPlan(QueryExplainer.java:134)
com.facebook.presto.sql.analyzer.QueryExplainer.getPlan(QueryExplainer.java:91)
com.facebook.presto.sql.analyzer.StatementAnalyzer.getQueryPlan(StatementAnalyzer.java:713)
com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:694)
com.facebook.presto.sql.analyzer.StatementAnalyzer.visitExplain(StatementAnalyzer.java:208)
com.facebook.presto.sql.tree.Explain.accept(Explain.java:66)
com.facebook.presto.sql.tree.AstVisitor.process(AstVisitor.java:22)
com.facebook.presto.sql.analyzer.Analyzer.analyze(Analyzer.java:60)
com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:254)
com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:240)
com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:204)
com.facebook.presto.execution.QueuedExecution.lambda$start$262(QueuedExecution.java:68)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
java.lang.Thread.run(Thread.java:745)

**Comment by martint** [comment] 2016-02-08 19:02
Duplicate of https://github.com/facebook/presto/issues/3979

**Closed by martint** 2016-02-08 19:02 UTC
Labels: bug
