### ISSUE TITLE
Optimize memory usage of map_agg

### ISSUE THREAD

**Issue by cberner** [facebook/presto#2788] opened 2015-04-25 01:50 UTC
`map_agg` relies on `KeyValuePairs` which always allocates a full `PageBuilder` this is very wasteful, as you may only be aggregating a few values into the map. We need to fix the TODO in `KeyValuePairs` to create an optimized version of `GroupByHash` that uses less memory

**Comment by yaoxin226** [comment] 2015-04-27 20:46
hi @cberner , I can take this issue if no one is working on it right now.

**Comment by cberner** [comment] 2015-04-27 20:47
That would be great! I don't think anyone is working on it

**Comment by yaoxin226** [comment] 2015-04-28 01:28
Some typical estimated memory of map_ag(bigint, varchar) right now(commit ab0c12acf). 
Seems like keyHash is the bottle neck here.

keyType | bigint
-----------|-------
size  |  1120 Bytes =  keyBlockBuilder.getSizeInBytes()  
keyBlockBuilder | FixedWidthBlockBuilder{positionCount=0, fixedSize=8, size=0}

valueType |varchar
-----------|-------
size | 5312 Bytes =  valueBlockBuilder.getSizeInBytes()  
valueBlockBuilder | VariableWidthBlockBuilder{positionCount=0, size=0}

keyHash | BigintGroupByHash
-----------|-------
size | 65536 Bytes  =  DEFAULT_MAX_BLOCK_SIZE_IN_BYTES
size  | 36960 Bytes  =  keysHash.getEstimatedSize()

**Comment by cawallin** [comment] 2015-07-29 03:45
@cberner -- duplicate of #2662 and complete :)

**Closed** 2015-07-29 14:31 UTC
