### ISSUE TITLE
Histogram function with map or array input cancels query

### ISSUE THREAD

**Issue by mattsfuller** [facebook/presto#3549] opened 2015-09-04 21:02 UTC
Getting some odd behavior with the Histogram aggregate function. When I run the query with map or array input, an error message "Query is gone (server restarted?)" is returned.

```
presto:sf1> select histogram(map(array [nationkey%3], array[regionkey])) from nation;
Query is gone (server restarted?)

presto:sf1> select histogram(array [nationkey%3, regionkey]) from nation;
Query is gone (server restarted?)

presto:sf1> select histogram(arr) from (select array [nationkey%3, regionkey] as arr from nation) T;
Query is gone (server restarted?)
```

Here is the stack trace I see. The Query was definitely not canceled by me:
```
com.facebook.presto.spi.PrestoException: Query was canceled
	at com.facebook.presto.execution.SqlQueryManager.cancelQuery(SqlQueryManager.java:321)
	at com.facebook.presto.server.StatementResource$Query.cancel(StatementResource.java:266)
	at com.facebook.presto.server.StatementResource.cancelQuery(StatementResource.java:214)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:151)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:171)
	at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:152)
	at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:104)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:387)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:331)
	at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:103)
	at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:297)
	at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:254)
	at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1030)
	at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:373)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:381)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:344)
	at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669)
	at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83)
	at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:300)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TraceTokenFilter.doFilter(TraceTokenFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at io.airlift.http.server.TimingFilter.doFilter(TimingFilter.java:52)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:499)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)
```

Here is an explain plan of one of the queries:
```
presto:sf1> explain select histogram(array [nationkey%3, regionkey]) from nation;
                                                         Query Plan                                                         
----------------------------------------------------------------------------------------------------------------------------
 - Output[_col0] => [histogram:map<array<bigint>,bigint>]                                                                   
         _col0 := histogram                                                                                                 
     - Aggregate(FINAL) => [histogram:map<array<bigint>,bigint>]                                                            
             histogram := "histogram"("histogram_3")                                                                        
         - Exchange[GATHER] => histogram_3:map<array<bigint>,bigint>                                                        
             - Aggregate(PARTIAL) => [histogram_3:map<array<bigint>,bigint>]                                                
                     histogram_3 := "histogram"("expr")                                                                     
                 - Project => [expr:array<bigint>]                                                                          
                         expr := "array_constructor"(("nationkey" % 3), "regionkey")                                        
                     - TableScan[tpch:tpch:nation:sf1.0, originalConstraint = true] => [nationkey:bigint, regionkey:bigint] 
                             nationkey := tpch:nationkey                                                                    
                             regionkey := tpch:regionkey                                                                    
                                                                                                                            
(1 row)

Query 20150902_051238_00061_jcraq, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0:00 [0 rows, 0B] [0 rows/s, 0B/s]
```

**Comment by dain** [comment] 2015-09-04 23:56
The `StatementClient` will send a `DELETE` HTTP request when `close` is called.  Maybe there is some error on the client side that is triggering the `close` call.  I would debug the cli.

**Comment by martint** [comment] 2015-10-10 19:01
I think this is due to a bug in the way maps with complex keys are serialized/deserialized between the coordinator and the CLI. See:

https://github.com/facebook/presto/pull/2740
https://github.com/facebook/presto/pull/3745

**Comment by martint** [comment] 2015-10-10 19:02
Closing as duplicate of https://github.com/facebook/presto/issues/3693

**Closed by martint** 2015-10-10 19:02 UTC
