### ISSUE TITLE
Querying in presto gives error logs with results

### ISSUE THREAD

**Issue by app-tarush** [facebook/presto#4267] opened 2016-01-04 17:58 UTC
[ERROR] Failed to disable interrupt character
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
	at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
	at jline.UnixTerminal.disableInterruptCharacter(UnixTerminal.java:153)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2445)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
	at com.facebook.presto.cli.LineReader.readLine(LineReader.java:51)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
	at com.facebook.presto.cli.Console.runConsole(Console.java:151)
	at com.facebook.presto.cli.Console.run(Console.java:130)
	at com.facebook.presto.cli.Presto.main(Presto.java:32)

[ERROR] Failed to disable litteral next character
java.lang.InterruptedException
	at java.lang.Object.wait(Native Method)
	at java.lang.Object.wait(Object.java:502)
	at java.lang.UNIXProcess.waitFor(UNIXProcess.java:396)
	at jline.internal.TerminalLineSettings.waitAndCapture(TerminalLineSettings.java:339)
	at jline.internal.TerminalLineSettings.exec(TerminalLineSettings.java:311)
	at jline.internal.TerminalLineSettings.stty(TerminalLineSettings.java:282)
	at jline.internal.TerminalLineSettings.undef(TerminalLineSettings.java:158)
	at jline.UnixTerminal.disableLitteralNextCharacter(UnixTerminal.java:185)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2448)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2372)
	at com.facebook.presto.cli.LineReader.readLine(LineReader.java:51)
	at jline.console.ConsoleReader.readLine(ConsoleReader.java:2360)
	at com.facebook.presto.cli.Console.runConsole(Console.java:151)
	at com.facebook.presto.cli.Console.run(Console.java:130)
	at com.facebook.presto.cli.Presto.main(Presto.java:32)

**Comment by haozhun** [comment] 2016-01-05 17:52
I believe this is a duplicate of #3654. And it has been recently fixed in #4222. It will go out in 0.132.

This is a bug in presto-cli (not presto server). Therefore, you need to upgrade you cli.

**Closed by haozhun** 2016-01-05 17:52 UTC

**Comment by app-tarush** [comment] 2016-01-05 18:06
Thanks Haozhun.

Regards,
Tarush
