### ISSUE TITLE
Explain on queries with timestamp literal fails

### ISSUE THREAD

**Issue by snarayanank2** [facebook/presto#3297] opened 2015-07-17 08:54 UTC
This is on v 0.105. Connected with redshift via Presto using the postgresql connector. Ran this explain query and it failed.

```
presto:default> explain select * from redshift.public.foo where ts < date '2015-01-01';
Query 20150717_082917_00013_kjwwm failed: cannot convert MethodHandle(ConnectorSession,long)Slice to (Object)Object
java.lang.invoke.WrongMethodTypeException: cannot convert MethodHandle(ConnectorSession,long)Slice to (Object)Object
        at java.lang.invoke.MethodHandle.asTypeUncached(MethodHandle.java:776)
        at java.lang.invoke.MethodHandle.asType(MethodHandle.java:770)
        at java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:633)
        at com.facebook.presto.sql.planner.PlanPrinter.formatDomain(PlanPrinter.java:617)
        at com.facebook.presto.sql.planner.PlanPrinter.printConstraint(PlanPrinter.java:578)
        at com.facebook.presto.sql.planner.PlanPrinter.access$200(PlanPrinter.java:88)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitTableScan(PlanPrinter.java:407)
        at com.facebook.presto.sql.planner.PlanPrinter$Visitor.visitTableScan(PlanPrinter.java:185)
        at com.facebook.presto.sql.planner.plan.TableScanNode.accept(TableScanNode.java:135)
        <snip>
```
PlanPrinter::formatDomain tries to convert domain to a printable string. The function to do this for timestamp is: 
```
    @ScalarOperator(CAST)
    @SqlType(StandardTypes.VARCHAR)
    public static Slice castToSlice(ConnectorSession session, @SqlType(StandardTypes.TIMESTAMP) long value)
```

This guy needs ConnectorSession instance which isn't available in PlanPrinter.

Please close it if it is already fixed in trunk.

**Comment by yuananf** [comment] 2015-07-17 09:09
This is the same as #3201

**Comment by zinking** [comment] 2015-08-03 02:07
works for TPCH
presto:sf1> explain select * from orders where orderdate < date '2015-01-01';
                                                                                                                                      Query Plan                                                          
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 - Output[orderkey, custkey, orderstatus, totalprice, orderdate, orderpriority, clerk, shippriority, comment] => [orderkey:bigint, custkey:bigint, orderstatus:varchar, totalprice:double, orderdate:date

**Comment by martint** [comment] 2015-10-10 19:21
Closing as duplicate of #3201

**Closed by martint** 2015-10-10 19:21 UTC
