### ISSUE TITLE
Writing a connector for a non-relational data store in presto

### ISSUE THREAD

**Issue by sumanth232** [facebook/presto#3222] opened 2015-07-06 14:11 UTC
How to write a connector for a non-relational data store without hard coding the columns of a table (like in example-http connector) as new columns can be added into a table in a non-relational database ?

**Comment by sumanth232** [comment] 2015-07-07 05:10
What is the efficient way to return the current set of columns ?
 For eg: if the data store contains JSON documents, and each JSON property is a column in the table, is it not very time consuming, to search all the docs for finding all the properties (columns) ?

As this method 'ConnectorMetadata.listTableColumns()' is called for every query, can this time consuming search be done to return the set of columns.
Does any other connector do this dynamic listing of columns ? If yes, can anybody tell me, how they do it efficiently ?

**Comment by petroav** [comment] 2015-07-10 22:24
I believe this is a duplicate of #3221 and was also discussed on the presto user mailing list.

**Closed** 2015-07-10 22:26 UTC
