### ISSUE TITLE
Field reference operator only works on qualified name references with a single level

### ISSUE THREAD

**Issue by BoatingClouds** [facebook/presto#2554] opened 2015-03-18 07:17 UTC
1. Desc table schema.
presto:test_db> desc test_orc_table;
   Column    |                                                                       Type                                                                        | Null | Partitio
-------------+---------------------------------------------------------------------------------------------------------------------------------------------------+------+---------
 uid         | varchar                                                                                                                                           | true | false
 information | ROW(Optional[name] varchar, Optional[gender] varchar, Optional[education] ROW(Optional[primary_school] varchar, Optional[middle_school] varchar)) | true | false
(2 rows)

2. Query Success.
presto:test_db> select uid, information from test_orc_table limit 3;
   uid   |                                                        information
---------+----------------------------------------------------------------------------------------------------------------------------
 100 | {name=Jack, gender=Male, education={primary_school=xx1, middle_school=xx2}}
 101 | {name=Lisa, gender=Female, education={primary_school=xx1, middle_school=xx2}}
 102 | {name=Todd, gender=Male, education={primary_school=xx1, middle_school=xx2}}
(5 rows)

3. Query Success.
presto:test_db> select uid, information.name from test_orc_table limit 3;
   uid   |                   name
---------+------------------------------------------
 100 | Jack
 101 | Lisa
 102 | Todd
(3 rows)

4. Query Failed.
presto:test_db> select uid, information.education.primary_school from test_orc_table limit 3;
Query 20140218_071429_00114_cqskj failed: Column 'information.education.primary_school' cannot be resolved

**Comment by cberner** [comment] 2015-03-25 23:19
This is a known issue with the way the field reference operator is implemented. It's super hacky right now. It looks like the issue is in `ExpressionAnalyzer.tryVisitRowFieldAccessor` on this line: `            QualifiedName base = new QualifiedName(node.getName().getParts().subList(0, node.getName().getParts().size() - 1));`

It's only stripping one level of the qualified name when doing the lookup, so probably what we need to do is keep stripping them until we find a match, and then possible patch `TranslationMap` as there's more handling of ROWs there. This will all go away when we rewrite the parsing of qualified names, to handle the "." as either an operator or a piece of a qualified name.

**Comment by cberner** [comment] 2015-03-25 23:22
@haozhun this low priority, but will give you a bunch of exposure to the parser and analyzer. When you've finished with your other tasks lets discuss with @martint the best way to fix this

**Comment by cberner** [comment] 2015-03-25 23:24
In the mean time, for anyone encountering this issue. I think you can work around it by adding parentheses, or using a subquery like

```
SELECT nested_row.my_field
FROM (
SELECT my_row_column.nested_row AS nested_row
FROM my_table
)
```

**Comment by cberner** [comment] 2015-08-18 18:13
Here's a test case:

```
assertQuery("SELECT a.col2.col0 FROM (VALUES ROW(test_row(1.0, ARRAY[2], test_row(3, 4.0)))) t(a)", "SELECT 3");
```

**Comment by joy-yao** [comment] 2015-10-16 20:55
This is fixed in https://github.com/facebook/presto/pull/3636

**Closed** 2015-10-24 18:55 UTC
