### ISSUE TITLE
Explain alter table fails with NPE

### ISSUE THREAD

**Issue by nileema** [facebook/presto#3420] opened 2015-08-07 05:23 UTC
`EXPLAIN ALTER TABLE foo RENAME TO foo1` fails with 
https://gist.github.com/nileema/9346f484359e39a52c21

**Comment by sogorkis** [comment] 2015-08-07 11:01
We are getting NPE for `EXPLAIN CREATE TABLE...` (without as `AS SELECT`) as well.

**Comment by cawallin** [comment] 2015-08-07 13:45
Duplicate of #1589

**Closed** 2015-08-07 14:22 UTC
