### ISSUE TITLE
Input symbols do not match output symbols

### ISSUE THREAD

**Issue by electrum** [facebook/presto#3939] opened 2015-11-10 21:11 UTC
```
java.lang.IllegalArgumentException: Input symbols do not match output symbols
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.<init>(ExchangeNode.java:71)
	at com.facebook.presto.sql.planner.optimizations.ProjectionPushDown$Rewriter.pushProjectionThrough(ProjectionPushDown.java:164)
	at com.facebook.presto.sql.planner.optimizations.ProjectionPushDown$Rewriter.visitProject(ProjectionPushDown.java:78)
	at com.facebook.presto.sql.planner.optimizations.ProjectionPushDown$Rewriter.visitProject(ProjectionPushDown.java:57)
	at com.facebook.presto.sql.planner.plan.ProjectNode.accept(ProjectNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitJoin(PlanVisitor.java:85)
	at com.facebook.presto.sql.planner.plan.JoinNode.accept(JoinNode.java:159)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitFilter(PlanVisitor.java:35)
	at com.facebook.presto.sql.planner.plan.FilterNode.accept(FilterNode.java:71)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitExchange(PlanVisitor.java:155)
	at com.facebook.presto.sql.planner.plan.ExchangeNode.accept(ExchangeNode.java:161)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.rewrite(PlanRewriter.java:100)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.lambda$defaultRewrite$130(PlanRewriter.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at com.facebook.presto.sql.planner.plan.PlanRewriter$RewriteContext.defaultRewrite(PlanRewriter.java:75)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:39)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.visitPlan(PlanRewriter.java:23)
	at com.facebook.presto.sql.planner.plan.PlanVisitor.visitOutput(PlanVisitor.java:50)
	at com.facebook.presto.sql.planner.plan.OutputNode.accept(OutputNode.java:81)
	at com.facebook.presto.sql.planner.plan.PlanRewriter.rewriteWith(PlanRewriter.java:28)
	at com.facebook.presto.sql.planner.optimizations.ProjectionPushDown.optimize(ProjectionPushDown.java:54)
	at com.facebook.presto.sql.planner.LogicalPlanner.plan(LogicalPlanner.java:98)
	at com.facebook.presto.execution.SqlQueryExecution.doAnalyzeQuery(SqlQueryExecution.java:266)
	at com.facebook.presto.execution.SqlQueryExecution.analyzeQuery(SqlQueryExecution.java:245)
	at com.facebook.presto.execution.SqlQueryExecution.start(SqlQueryExecution.java:209)
	at com.facebook.presto.execution.QueuedExecution.lambda$start$201(QueuedExecution.java:68)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by haozhun** [comment] 2015-11-10 21:12
Duplicate of 3937

**Closed by haozhun** 2015-11-10 21:12 UTC
Labels: bug, RELEASE-BLOCKER
